# Copyright (c) Meta Platforms, Inc. and affiliates.

packages:
  - "apps/*"
  - "packages/*"
  - "packages/themes/*"
  - "internal/*"

minimumReleaseAge: 10080
minimumReleaseAgeExclude:
  - "@astryxdesign/*"
