// Copyright (c) Meta Platforms, Inc. and affiliates.

// Copyright (c) Meta Platforms, Inc. and affiliates.

/**
 * XDS Default Theme
 *
 * The reference theme — provides the standard XDS visual language.
 * Uses defineTheme for CSS-based theming (no StyleX build required for consumers).
 *
 * Typography sizing is driven by typography.scale, which auto-generates both
 * the token values (--text-heading-1-size, --text-body-size, etc.) and the
 * component override rules (.xds-heading.level-1 { font-size: ... }).
 *
 * Only non-typography component overrides need to be specified manually.
 */

import {defineTheme, defineSyntaxTheme} from '@xds/core/theme';
import {defaultIconRegistry} from './icons';

/**
 * Default syntax palette — GitHub Light (light) + GitHub Dark (dark).
 *
 * Color values sourced from the GitHub VS Code theme by the Primer team.
 * Original theme: https://github.com/primer/github-vscode-theme (MIT license).
 */
const defaultSyntax = defineSyntaxTheme({
  name: 'xds-default',
  tokens: {
    keyword: ['#cf222e', '#ff7b72'],
    string: ['#0a3069', '#a5d6ff'],
    comment: ['#6e7781', '#8b949e'],
    number: ['#0550ae', '#79c0ff'],
    function: ['#8250df', '#d2a8ff'],
    type: ['#953800', '#ffa657'],
    variable: ['#24292f', '#e6edf3'],
    operator: ['#cf222e', '#ff7b72'],
    constant: ['#0550ae', '#79c0ff'],
    tag: ['#116329', '#7ee787'],
    attribute: ['#0550ae', '#79c0ff'],
    property: ['#0550ae', '#79c0ff'],
    punctuation: ['#24292f', '#c9d1d9'],
    background: ['#ffffff', '#0d1117'],
  },
});

export const defaultTheme = defineTheme({
  name: 'default',

  // Typography: base=14px, ratio=1.2, h4 anchored to base.
  // Generates all heading + text tokens AND component overrides automatically.
  typography: {scale: {base: 14, ratio: 1.2}},

  // Motion: base durations from Ted's proposal (#674), ratio=0.75.
  // Generates: fast-min=130ms, fast=175ms, fast-max=235ms,
  //            medium-min=310ms, medium=410ms, medium-max=545ms.
  motion: {fast: 175, medium: 410, slow: 975, ratio: 0.75},

  // Syntax highlighting — tuned to the default palette
  syntax: defaultSyntax,

  // The default theme uses the built-in token defaults from tokens.stylex.ts.
  tokens: {},

  components: {
    // =========================================================================
    // Button
    // =========================================================================
    button: {
      'variant:secondary': {
        backgroundColor:
          'light-dark(rgba(5, 54, 89, 0.1), rgba(223, 226, 229, 0.2))',
      },
    },

    // Heading and text component overrides are auto-generated by typography.scale.
    // No manual heading: { ... } or text: { ... } blocks needed.
  },

  // =========================================================================
  // On-media overrides
  // =========================================================================
  // Customize how components look on inverted surfaces (e.g. dark toast on
  // a light page). color-scheme + base token overrides are provided by
  // default; these add component-level adjustments.

  onDark: {
    components: {
      button: {
        'variant:secondary': {
          backgroundColor: 'color-mix(in srgb, white 20%, transparent)',
        },
      },
    },
  },

  onLight: {
    components: {
      button: {
        'variant:secondary': {
          backgroundColor: 'color-mix(in srgb, black 10%, transparent)',
        },
      },
    },
  },

  icons: defaultIconRegistry,
});
